export const CART_ACTION_TYPES = {
  SET_TO_CART: "cart/SET_TO_CART",
  SET_SIZE: "cart/SET_SIZE",
  SET_REMOVE_ITEM: "cart/SET_REMOVE_ITEM",
  SET_ADD_QTY: "cart/SET_ADD_QTY",
  SET_DECREASE_QTY: "cart/SET_DECREASE_QTY",
  SET_UPDATE_SUMMARY: "cart/SET_UPDATE_SUMMARY"
};